DROP TABLE IF EXISTS `layers`;
CREATE TABLE IF NOT EXISTS  `layers` (
id INT(11) NOT NULL,
name VARCHAR(40) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
) ENGINE = INNODB, CHARACTER SET utf8 COLLATE utf8_bin;

DROP TABLE IF EXISTS `user_layers`;
CREATE TABLE IF NOT EXISTS `user_layers` (
user_id INT(11) NOT NULL,
layer_id INT(11) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (user_id, layer_id),
FOREIGN KEY (layer_id) REFERENCES layers (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB, CHARACTER SET utf8 COLLATE utf8_bin;
